#!/usr/bin/python3
"""test module for testing file storage"""

import unittest
from models.base_model import BaseModel
from models.engine.file_storage import FileStorage
from models import storage


class TestFileStorage(unittest.TestCase):
    """test class testing file storage"""


    def test_type(self):
        """check FileStorage type"""
        self.assertIsInstance(storage, FileStorage)
        self.assertEqual(type(storage), FileStorage)

    def test_save_arg(self):
        with self.assertRaises(TypeError):
            models.storage.save(None)

    def test_reload_with_no_file(self):
        self.assertRaises(FileNotFoundError, models.storage.reload())


if __name__ == '__main__':
    unittest.main()
